baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
theme = "hugo-theme-nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "Linkforce"
user = "linkforce"
hostname = "linkforce.fi"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
#key = 0
#name = "github"
#url = "https://github.com/gohugoio"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/linkforce_SWE"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/pobystrom/"

[[params.social]]
key = 3
name = "email"
url = "mailto:info@linkforce.fi"
